### PR TITLE
Adds adler32sum function and test

### PR DESCRIPTION
**Pull request by marshallford**
Just like the title says: Adds an alder32sum function, test, and docs entry.

### CODE REVIEW

**Comment by mattfarina** [comment]
@marshallford Thanks for the pull request. Do you have a user story or reason you can share for this one? I'm curious where an alder32sum will be used.

**Comment by marshallford** [comment]
@mattfarina The Kubernetes community uses Adler-32 [occasionally](https://github.com/jetstack/cert-manager/blob/6a54aad5d32af7342951f4c8944e7c79ffa979b5/pkg/issuer/acme/http/pod.go#L34) for a fast checksum. This Addition would be useful for templating out labels based on the checksum when using a tool like [Helm](https://github.com/helm/helm).

**Comment by marshallford** [comment]
@mattfarina just a friendly nudge

**Comment by marshallford** [comment]
Could you cut a release that includes this merge? Thank you.

**Pull request merged**
