### PR TITLE
replace satori/go.uuid with google/uuid

### PR DESCRIPTION
**Pull request by petterw**
A breaking change was introduced by the commit
https://github.com/satori/go.uuid/commit/0ef6afb

### CODE REVIEW

**Comment by petterw** [comment]
closing and reopening to retrigger timed out build

**Comment by petterw** [comment]
Sorry for the spam. Seems travis is having problems https://www.traviscistatus.com/incidents/lrc4yp46t8wb

**Comment by mattfarina** [comment]
@petterw Is there a reason other than the breaking change to switch to googles implementation?

@technosophos any thoughts?

**Comment by petterw** [comment]
Not that I know of, I just made this PR because satori was not answering requests for tagging for some days.

**Comment by reddec** [comment]
May I ask you about when this PR will be merged?
It's looks like very good solution to prevent another breaking changes from @satori

**Comment by lucasmlofaro** [comment]
This should be the accepted solution in favor of keeping up with the `go.uuid` package. Since there is only one place it is used in the code and all it does is generate a new UUID it would make sense to use a more reliable package for this purpose. We would appreciate this PR getting merged ASAP.

**Comment by mattfarina** [comment]
There are two things I'm hoping someone can help me with:

1. Some time ago `go.uuid` tagged a release for 1.2.0 that didn't include the break. It doesn't appear that any tagged release ever had the breaking change (If I'm missing something please let me know). Semantic Versioning hasn't been violated. As long as the breaking change is released as version 2, what's the issue with a breaking change that's not released?
1. Is there a reason that `google/uuid` would be better? We're open to switching but are interested in a reason that's useful to spring and it's end users.

**Comment by nemosupremo** [comment]
@mattfarina 

Regarding 1, the issue is `go.uuid`'s *master* branch includes the breaking change, which breaks `go get`. Obviously `go get` sucks for this reason and we should all be masters of our own destiny, but its still widely used. For example, [hermes](https://github.com/matcornic/hermes) depends on this package, and its install instructions listed in it's README are `go get -u github.com/matcornic/hermes` which fails because it pulls both the master branch of `sprig` and `go.uuid`:

```
$ docker run -it golang:1.9
root@73fae6303e00:/go# go get -u github.com/matcornic/hermes
# github.com/Masterminds/sprig
src/github.com/Masterminds/sprig/crypto.go:35:37: multiple-value uuid.NewV4() in single-value context
root@73fae6303e00:/go#
```

Again, I understand how `go get` depending on the master branch isn't ideal, but the reality is it breaks a commonly used workflow.

Regarding 2, both libraries are the same - sprig, only uses them to generate uuids, which are then immediately converted into strings. Both the new `go.uuid` and `google/uuid` have similar semantics regarding `New` (in both cases, you can choose to panic, or handle the error, an error which almost never happens, and likely in this case we would choose to panic given how extremely rare the error case is).

If I had to choose one that was better for sprig's users, I would go with `google/uuid`. It's not strictly technically better, but I can't help but feel the maintainer of `go.uuid` broke the trust of other users for a very trivial reason (See satori/go.uuid#66). The API had been stable for years, *thousands* of projects were affected, and this is something he did with little warning, and to this day people are finding projects that have to be fixed. While again, most of us understand its dangerous to depend on the master branch, I think, in turn maintainers have been responsible for communicating and working with the community on breaking changes. In this case, it also would have been trivial to provide a backwards compatible change instead of breaking other projects. I believe `go.uuid`'s change was pretty reckless and users of `sprig` would probably prefer not depending on library that breaks the build for such a minor functionality.

**Comment by technosophos** [comment]
I've been pretty happy with Satori's UUID. But honestly it's been a while since that repo made a major breaking change, and there's still not response from the owner on getting a tagged release out. So... I think at this point we are best served by switching to the other library.

**Comment by petterw** [comment]
I think they appveyor stuff broke for unrelated reasons. Let me know if you need anything else from me.

**Comment by mattfarina** [comment]
@petterw I'll work out the appveyor issues (not related to this), merge this PR, and then cut a release. Thanks for the rebase.

**Pull request merged**
