### PR TITLE
Properly handle errors

### LINKED ISSUE #115: Silently omitting errors
There are cases when errors are not handled but it could be useful for debugging compilation errors. See [1](https://github.com/Masterminds/sprig/blob/77bb58b7f5e10889a1195c21b9e7a96ee166f199/defaults.go#L65), [2](https://github.com/Masterminds/sprig/blob/77bb58b7f5e10889a1195c21b9e7a96ee166f199/dict.go#L83), [3](https://github.com/Masterminds/sprig/blob/77bb58b7f5e10889a1195c21b9e7a96ee166f199/date.go#L74)

In some cases it is pretty much all right to return default-*ish* values silently but in some cases it would be useful to fail and print the error message.

Proposal:
- extend the existing API and introduce {func}E versions of some funcs like it is done here https://github.com/spf13/cast

### LINKED ISSUE #125: Replace panics with errors?
Somewhat related to #115... but there are places where the functions panic instead of returning an error (particularly in https://github.com/Masterminds/sprig/blob/master/list.go). Maybe I'm missing something, but is there a good reason for this?

I'm catching the panics, but as a result I don't get any useful context information from text/template about where in the template it failed other than the error message.

### PR DESCRIPTION
**Pull request by nrvnrvn**
* tried to satisfy the god of linters;
* replaced explicit and "inherited" panics with error returns (fixes #125), this actually makes much more sense;
* introduced new functions: `mustDateModify`, `mustToDate`, `mustToJson`, `mustToPrettyJson`, `mustMerge` (fixes #115);
* replaced type cast functions with spf13/cast to DRY and not re-invent anything. If for some reason you find this change should be reverted please let me know

### CODE REVIEW

**Comment by nrvnrvn** [comment]
@mattfarina @technosophos
hey guys! Could you please take a look?

**Comment by technosophos** [comment]
I am torn on this PR because it fixes a number of things that I think need to be fixed, but it significantly changes the public API -- which means we'd have to rev the major version number.

Thoughts, @mattfarina ?

**Comment by mattfarina** [comment]
I want to think through the idea of incrementing the major version. Here is [a list of public packages that use sprig](https://godoc.org/github.com/Masterminds/sprig?importers). I'm sure this isn't complete as everything doesn't land in godoc.

When I look at the list I wonder about the impact to Traefik, OpenShift, the things Rancher is doing, and others. Is this change worth incrementing the public API for them? Is there another set of public API changes we might want to make to increase the value of changing the API?

I also got to learn about https://www.runatlantis.io/ by looking at who uses it.

**Comment by mattfarina** [comment]
@nrvnrvn I pulled your commits into #189 and then made some changes. The public Go API is no longer changed. There are now two sets of functions. Those with the previous behavior and those prefixed with `must` for the errors following the pattern you started. There are people who want it both ways so we were looking to do that.

This was automatically marked as merged because the commits were merged.

Thanks for the work.

**Comment by nrvnrvn** [comment]
Thanks a lot @mattfarina

**Pull request merged**
