### PR TITLE
Add `chunk` function to split array into smaller

### PR DESCRIPTION
**Pull request by karelbilek**
this was a function that I found helpful to have.

I tried to follow your style.

### CODE REVIEW

**Comment by technosophos** [comment]
Should the order of arguments be reversed? One of the things we've tried to do is make it easier to pipe data from one command to the next. Doing `tuple 1 2 3 4 5 | chunk 3` feels a little more ergonomic than using a variable in between.

**Comment by karelbilek** [comment]
Oh sure. I rarely use piping and use vars instead so I forgot about this usecase.

**Comment by karelbilek** [comment]
changed, rebased

**Review by technosophos — APPROVED** [review]
Looks great! Thank you.

**Pull request merged**
