### PR TITLE
Added ceil floor and round functions

### PR DESCRIPTION
**Pull request by alanquillin**
per request: https://github.com/Masterminds/sprig/issues/34

### CODE REVIEW

**Comment by adnaan** [comment]
Need these functions! Going ahead with copy-pasta for now.

**Comment by technosophos** [comment]
Definitely! Can you add some docs for these here? https://github.com/Masterminds/sprig/blob/master/docs/math.md

**Comment by alanquillin** [comment]
@technosophos documentation has been added.

**Comment by technosophos** [comment]
Excellent. Thanks for doing the documentation updates.

**Pull request merged**
