### PR TITLE
Added the loop function

### PR DESCRIPTION
**Pull request by eicnix**
The loop function allows to iterate over a template n times while allowing the usage of an index variable. 

Upon execution the function creates a zero filled slice for the provided size that can used in combination with the range function.

### CODE REVIEW

**Comment by technosophos** [comment]
Is this different from the `until` function?

**Comment by lukaseichler** [comment]
I did not find the `until` function but its a duplicate then.

**Comment by eicnix** [comment]
I did not find the `util` function before so I am closing this PR.

**Comment by technosophos** [comment]
Cool. Thanks. I definitely appreciate your contributing. I probably should have put the docs in the control structures section instead of in the integer slices documentation. Sorry about that.

**Pull request closed without merging**
