### PR TITLE
Fix links to other markdown docs.

### PR DESCRIPTION
**Pull request by chancez**

### CODE REVIEW

**Comment by technosophos** [comment]
The intention was to use this: http://masterminds.github.io/sprig/

**Comment by chancez** [comment]
How is that rendered? Generally relative markdown links work with github/github pages, it will use the .html url once rendered.

**Comment by chancez** [comment]
https://github.com/blog/1395-relative-links-in-markup-files

**Comment by technosophos** [comment]
Okay. If you can rebase, I'll merge and we'll see if that works with docs.

**Comment by chancez** [comment]
Rebased

**Comment by technosophos** [comment]
Seems to have worked! Thanks.

**Pull request merged**
